version: '3.1'
services:
  mysql:
    container_name: mysql-docker
    image: mysql:8.0.30
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=senhaDoDB
      - MYSQL_USER=delivery
      - MYSQL_PASSWORD=senhaDoDB
    volumes:
      - volume-mysql:/var/lib/mysql
volumes:
  volume-mysql: